baseURL: "https://glistening-banoffee-cc19f7.netlify.app/"
languageCode: en-us
title: Blluerssoap
theme: PaperMod

menu:
  main:
    - identifier: products
      name: Products
      url: /products/
      weight: 10
    - identifier: about
      name: About us
      url: /about-us/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

params:
   ShowBreadCrumbs: true
   ShowShareButtons: true
